import type { Service } from '@/types'

export const SERVICES: Service[] = [
  {
    slug:        'ai-readiness-audit',
    label:       'AI Readiness Audit',
    badge:       'Quick Start',
    badgeVariant:'featured',
    icon:        '◎',
    problem:     'Nereden başlayacağını bilmemek',
    title:       'AI Readiness Audit',
    description: 'Şirketinizin AI olgunluğunu ve büyüme fırsatlarını ölçeriz.',
    output:      'AI Readiness Score + Öncelik Haritası + 90 Gün Roadmap',
    tags:        ['CEO & Yönetim', '2–3 Hafta'],
    cta:         'Audit Başlat',
    duration:    '2–3 Hafta',
    for:         'CEO, CTO, CMO',
  },
  {
    slug:        'ceo-workshop',
    label:       'Executive Workshop',
    badge:       'CEO Favorite',
    badgeVariant:'ceo',
    icon:        '◈',
    problem:     'Yanlış sorular sormak',
    title:       'Executive Workshop',
    description: 'Liderlik ekibiniz AI\'a doğru çerçeveden bakıyor mu?',
    output:      'Strateji Planı + Aksiyon + Ekip Hizalaması',
    tags:        ['C-Suite', '1 Gün'],
    cta:         'Workshop Talep Et',
    duration:    '1 Gün',
    for:         'C-Suite, Liderlik Ekibi',
  },
  {
    slug:        'growth-blueprint',
    label:       'AI Strategy Sprint',
    badge:       'Popular',
    badgeVariant:'popular',
    icon:        '▣',
    problem:     'Stratejisiz büyüme',
    title:       'AI Strategy Sprint',
    description: '90 günlük somut büyüme planı. Haftalık adımlar, metrikler.',
    output:      '90 Günlük Blueprint + KPI Dashboard',
    tags:        ['Kurucular', '6 Hafta'],
    cta:         'Sprint Başlat',
    duration:    '6 Hafta',
    for:         'Kurucular, CMO',
  },
  {
    slug:        'geo-program',
    label:       'AI Growth Systems',
    badge:       'GEO',
    badgeVariant:'geo',
    icon:        '◇',
    problem:     'AI aramalarında görünmemek',
    title:       'AI Growth Systems',
    description: 'ChatGPT, Gemini, Perplexity\'de markanız önerilsin.',
    output:      'GEO Görünürlük Artışı + Aylık Rapor',
    tags:        ['Pazarlama', '90 Gün'],
    cta:         'GEO Programı',
    duration:    '90 Gün',
    for:         'Pazarlama, İçerik Ekipleri',
  },
  {
    slug:        'agent-strategy',
    label:       'AI Agent Strategy',
    badge:       'Enterprise',
    badgeVariant:'enterprise',
    icon:        '◉',
    problem:     'Agent nereye kurulacak?',
    title:       'AI Agent Strategy',
    description: 'Doğru süreçlere doğru agent. Mimari ve prototip.',
    output:      'Agent Mimari Planı + Prototip',
    tags:        ['CTO & Ürün', '8–12 Hafta'],
    cta:         'Agent Stratejisi',
    duration:    '8–12 Hafta',
    for:         'CTO, Ürün Ekibi',
  },
  {
    slug:        'executive-advisory',
    label:       'Executive Advisory',
    badge:       'CEO Favorite',
    badgeVariant:'ceo',
    icon:        '◑',
    problem:     'AI kararlarında yalnız kalmak',
    title:       'Executive Advisory',
    description: 'CEO ve kuruculara aylık güvenilir dış perspektif.',
    output:      'Aylık 2×90 Dk + Async Destek',
    tags:        ['CEO & Founders', 'Aylık'],
    cta:         'Advisory Başvur',
    duration:    'Aylık Retainer',
    for:         'CEO, Kurucular',
  },
]

export function getService(slug: string): Service | undefined {
  return SERVICES.find(s => s.slug === slug)
}
